"use client";

import { Grid2X2, List, Search, SlidersHorizontal } from "lucide-react";

type Props = { query: string; category: string; availability: "all" | "available" | "out"; categories: string[]; view: "table" | "grid"; onQueryChange: (value: string) => void; onCategoryChange: (value: string) => void; onAvailabilityChange: (value: "all" | "available" | "out") => void; onViewChange: (view: "table" | "grid") => void };

export default function BookFilterBar({ query, category, availability, categories, view, onQueryChange, onCategoryChange, onAvailabilityChange, onViewChange }: Props) {
  return <div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm md:flex-row md:items-center"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17} /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Search title, author, or ISBN" className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-3 text-sm outline-none transition focus:border-blue-400 focus:bg-white" /></div><div className="flex flex-wrap items-center gap-2"><SlidersHorizontal size={16} className="text-slate-400" /><select value={category} onChange={(event) => onCategoryChange(event.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none"><option value="">All categories</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select><select value={availability} onChange={(event) => onAvailabilityChange(event.target.value as Props["availability"])} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none"><option value="all">All stock</option><option value="available">Available only</option><option value="out">Out of stock</option></select><div className="flex rounded-xl border border-slate-200 p-1"><button type="button" title="Table view" onClick={() => onViewChange("table")} className={`rounded-lg p-2 ${view === "table" ? "bg-slate-100 text-slate-900" : "text-slate-400"}`}><List size={16} /></button><button type="button" title="Grid view" onClick={() => onViewChange("grid")} className={`rounded-lg p-2 ${view === "grid" ? "bg-slate-100 text-slate-900" : "text-slate-400"}`}><Grid2X2 size={16} /></button></div></div></div>;
}
