"use client";

import { BookOpen, MapPin, X } from "lucide-react";
import AvailabilityBadge from "./AvailabilityBadge";
import type { Book } from "@/types/book";

export default function BookDetailsModal({ book, onClose, onEdit }: { book: Book; onClose: () => void; onEdit: () => void }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-lg rounded-2xl bg-white shadow-2xl"><div className="flex justify-end p-4 pb-0"><button type="button" onClick={onClose} title="Close" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={19} /></button></div><div className="px-6 pb-6">{book.coverImage ? <div role="img" aria-label={`${book.title} cover`} className="mb-5 h-36 w-full rounded-xl bg-cover bg-center" style={{ backgroundImage: `url(${book.coverImage})` }} /> : <div className="mb-5 flex h-36 items-center justify-center rounded-xl bg-gradient-to-br from-slate-900 to-blue-900 text-white"><BookOpen size={48} strokeWidth={1.2} /></div>}<div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold text-slate-900">{book.title}</h2><p className="mt-1 text-slate-500">{book.author}</p></div><AvailabilityBadge availableCopies={book.availableCopies} totalCopies={book.totalCopies} /></div><div className="mt-6 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">ISBN</p><p className="mt-1 font-medium text-slate-800">{book.isbn}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Category</p><p className="mt-1 font-medium text-slate-800">{book.category}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Publication</p><p className="mt-1 font-medium text-slate-800">{book.publisher || "-"} {book.publishedYear ? `(${book.publishedYear})` : ""}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Location</p><p className="mt-1 flex items-center gap-1 font-medium text-slate-800"><MapPin size={14} />{book.shelfLocation || "Unassigned"}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Borrow history</p><p className="mt-1 font-medium text-slate-800">{book._count?.borrowRecords ?? 0} transaction(s)</p></div></div>{book.description && <p className="mt-5 text-sm leading-6 text-slate-600">{book.description}</p>}<button type="button" onClick={onEdit} className="mt-6 w-full rounded-xl bg-slate-900 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">Edit book</button></div></div></div>;
}
